"""
Generate the sin/cos/rho ROMs for the FPGA log-polar core, and provide a
BIT-EXACT golden model of the hardware datapath.

Fixed-point contract (must match logpolar_core.v exactly):
    cos_lut[t] = round(cos(2*pi*t/NTHETA) * 2^14)   signed 16-bit  (Q2.14)
    sin_lut[t] = round(sin(2*pi*t/NTHETA) * 2^14)   signed 16-bit  (Q2.14)
    rho_lut[j] = round(exp(j/M)          * 2^8 )    unsigned 16-bit(Q8.8)
                 with M = NRHO / ln(MAX_RADIUS)

    xoff = (rho_lut * cos_lut + 2^21) >> 22     arithmetic shift, round-to-nearest
    x    = CX + xoff
    y    = CY + yoff
    dst[t][j] = src[y][x]                        (nearest neighbour)
"""
import math
import numpy as np

# ---------------- geometry / format parameters ----------------
IMG_W = IMG_H = 128
NTHETA = 128          # output rows    (angle)
NRHO = 128            # output columns (log radius)
CX = CY = 64          # sampling centre in source image
MAX_RADIUS = 63.0     # radius reached by the outermost column

TRIG_FRAC = 14        # Q2.14
RHO_FRAC = 8          # Q8.8
PROD_FRAC = TRIG_FRAC + RHO_FRAC   # 22


def build_luts():
    cos_lut, sin_lut = [], []
    for t in range(NTHETA):
        a = 2.0 * math.pi * t / NTHETA
        cos_lut.append(int(round(math.cos(a) * (1 << TRIG_FRAC))))
        sin_lut.append(int(round(math.sin(a) * (1 << TRIG_FRAC))))

    M = NRHO / math.log(MAX_RADIUS)
    rho_lut = [int(round(math.exp(j / M) * (1 << RHO_FRAC))) for j in range(NRHO)]

    assert all(-32768 <= v <= 32767 for v in cos_lut + sin_lut)
    assert all(0 <= v <= 65535 for v in rho_lut)
    return cos_lut, sin_lut, rho_lut, M


def _rnd_shift(prod):
    """Round-to-nearest arithmetic right shift, exactly as the RTL does."""
    return (prod + (1 << (PROD_FRAC - 1))) >> PROD_FRAC   # Python >> is arithmetic


def golden_transform(src):
    """Bit-exact model of logpolar_core.v. src: (128,128) uint8 -> (128,128) uint8."""
    cos_lut, sin_lut, rho_lut, _ = build_luts()
    dst = np.zeros((NTHETA, NRHO), dtype=np.uint8)
    for t in range(NTHETA):
        for j in range(NRHO):
            x = CX + _rnd_shift(rho_lut[j] * cos_lut[t])
            y = CY + _rnd_shift(rho_lut[j] * sin_lut[t])
            if 0 <= x < IMG_W and 0 <= y < IMG_H:
                dst[t][j] = src[y][x]
            else:
                dst[t][j] = 0
    return dst


def addr_extremes():
    """Sanity: report the x/y range actually produced, to confirm no clipping."""
    cos_lut, sin_lut, rho_lut, _ = build_luts()
    xs, ys = [], []
    for t in range(NTHETA):
        for j in range(NRHO):
            xs.append(CX + _rnd_shift(rho_lut[j] * cos_lut[t]))
            ys.append(CY + _rnd_shift(rho_lut[j] * sin_lut[t]))
    return min(xs), max(xs), min(ys), max(ys)


def emit_verilog(path):
    cos_lut, sin_lut, rho_lut, M = build_luts()

    def rom(name, vals, signed, width=16):
        lines = [f"// ---------------------------------------------------------------",
                 f"// {name}: {len(vals)} x {width}-bit "
                 f"{'signed' if signed else 'unsigned'} ROM (auto-generated)",
                 f"// ---------------------------------------------------------------",
                 f"module {name} (",
                 f"    input  wire       clk,",
                 f"    input  wire [6:0] addr,",
                 f"    output reg {'signed ' if signed else ''}[{width-1}:0] dout",
                 f");",
                 f"    always @(posedge clk) begin",
                 f"        case (addr)"]
        for i, v in enumerate(vals):
            enc = v & 0xFFFF
            lines.append(f"            7'd{i:<3}: dout <= 16'h{enc:04X};   // {v}")
        lines.append(f"            default: dout <= 16'h0000;")
        lines.append("        endcase")
        lines.append("    end")
        lines.append("endmodule")
        return "\n".join(lines)

    header = f"""`timescale 1ns / 1ps
// =================================================================
//  logpolar_luts.v  --  AUTO-GENERATED by scripts/logpolar/gen_luts.py
//  DO NOT EDIT BY HAND. Re-run the generator to change geometry.
//
//  NTHETA      = {NTHETA}      (output rows,    angle 0..2pi)
//  NRHO        = {NRHO}      (output columns, log radius)
//  MAX_RADIUS  = {MAX_RADIUS}
//  M           = NRHO/ln(MAX_RADIUS) = {M:.6f}
//  trig format = Q2.14 signed
//  rho  format = Q8.8  unsigned
// =================================================================

"""
    with open(path, "w") as f:
        f.write(header)
        f.write(rom("cos_rom", cos_lut, signed=True) + "\n\n")
        f.write(rom("sin_rom", sin_lut, signed=True) + "\n\n")
        f.write(rom("rho_rom", rho_lut, signed=False) + "\n")


if __name__ == "__main__":
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "rtl/logpolar/logpolar_luts.v"
    emit_verilog(out)
    xmin, xmax, ymin, ymax = addr_extremes()
    print(f"wrote {out}")
    print(f"source x range: {xmin}..{xmax}   y range: {ymin}..{ymax}  (must be 0..127)")
